# Generated by Django 5.2.8 on 2025-11-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_complted',
            new_name='is_completed',
        ),
    ]
